### ISSUE TITLE
Arrangør og media mangler e-post og telefonnummer?

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMrapporter#105]
Når man laster ned rapport under alle innslag og huker av for kontaktinformasjon med e-post, telefonnummer og alder, så kommer ikke dette opp i rapporten på ARRANGØRENE og MEDIA-deltagere.

Support:83154

**Comment by slogan-15** [comment]
Det ser ut som det er bare alder som ikke kommer i rapporten.
