### ISSUE TITLE
Nedlasting av rapport i kurs-kommune feil

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMrapporter#109]
Mulig at det feiler også i andre kommuner - ikke testet.

Support#84454

**Comment by mariusmandal** [comment]
Kan det være fordi rapporten peker til http://download.ukm.no og ikke https?

**Comment by mariusmandal** [comment]
For å finne feilen:

- Velg en kommune
- Velg et arrangement
- Gå til rapporter
- Velg en rapport (f.eks. "Alle innslag")
- Trykk "generer rapport"
- Trykk "last ned som word"
- Den grønne knappen som det står "last ned filen" har feil url

**Comment by mariusmandal** [comment]
Fix er merget til master, og @jardarn tar kontakt med en av de som har meldt feilen til support for å se om dette løser problemet.

**Comment by jardarn** [comment]
Lukker denne da vedkommende som meldte om dette ikke har svart på henvendelsen. Dette var en person fra et produksjonsselskap som heller ikke har bruker på ukm.no.
