### ISSUE TITLE
Tilgjengeliggjør rapportene

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMrapporter#119]
Det må være lettere å velge maler enn det er i dag

**Comment by mariusmandal** [comment]
# Finne tilbake til problemet

- Logg inn
- Velg et fylke
- Velg et arrangement
- Velg en rapport

HER burde du ha en kjapp måte å velge mal på, og det burde være like opplagt som å krysse av alle boksene.

Det bør også være mer synlig hvordan man lagrer en oppdatering, eller en ny rapport

**Comment by mariusmandal** [comment]
@slogan-15 kan du se på hvordan du vil løse denne? (når vi er i gang med sprinten, ikke akkurat nå 😉)

**Comment by slogan-15** [comment]
![New Wireframe 1](https://user-images.githubusercontent.com/10181004/116259551-30b3c780-a776-11eb-86ff-9b6ff70a893c.png)


![New Wireframe 2](https://user-images.githubusercontent.com/10181004/116259561-327d8b00-a776-11eb-9c66-88d2e0196156.png)

Hva synes du @mariusmandal 🙂

**Comment by mariusmandal** [comment]
Foreslår to ulike varianter @slogan-15 , avhengig av hvor mange maler brukeren har laget:

**Hvis mindre enn fem maler:**
![noen_maler](https://user-images.githubusercontent.com/4747102/116699981-867eae80-a9c6-11eb-85d3-cdd9beb11bc3.png)


**Hvis mer enn fem maler**
![mange_maler](https://user-images.githubusercontent.com/4747102/116699999-8bdbf900-a9c6-11eb-91a0-4177148801da.png)


I tillegg bør knappen "lagre som mal" (i bunn av siden) bli blå (`btn-primary`), mens "generer rapport" må bli grønn (`btn-success`)

**Comment by mariusmandal** [comment]
<img width="414" alt="Skjermbilde 2021-05-25 kl  11 57 25" src="https://user-images.githubusercontent.com/4747102/119479443-f0357280-bd50-11eb-8114-07fcdc1eec9c.png">

Når brukeren ikke har rapporter, kan det ikke stå "vis rapport fra mal" @slogan-15
