### ISSUE TITLE
Rapporter bør ha fylkeskontaktinfo

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMrapporter#12]
Tekniske prøver burde ha med fylkeskontakt i rapport i tillegg til deltakere og innslag
Fra @torsteinsiegel

**Comment by AsgeirSH** [comment]
![skjermbilde 2016-02-25 kl 16 38 48](https://cloud.githubusercontent.com/assets/1831028/13324489/49f8d820-dbde-11e5-9cb1-acfb9715b806.png)
Holder det med Word-rapporten, som på bildet? Eller bør det også inn i HTML og Excel? (Da risikerer vi jo at de sender SMS til seg selv etc?)

**Comment by mariusmandal** [comment]
Går vel an å legge det inn i html-forsiden (som i Word) så det blir med i utskrift, men i excel bør det ikke være med :)



Mvh,


Marius Mandal

92837360

mariusmandal@gmail.com


—Sent from Mailbox

**Comment by AsgeirSH** [comment]
@mariusmandal Ganske sexy teknisk løsning på denne - verdt å browse commiten for å kikke :)

**Comment by mariusmandal** [comment]
@AsgeirSH pent!
