### ISSUE TITLE
Egenkomponert + instrumental må inn i rapporter

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMrapporter#20]
I alle rapporter som omhandler innslaget må teksten "egenkomponert" + "instrumental" inkluderes på fornuftig måte.

**Comment by mariusmandal** [comment]
- [ ] program
- [ ] tekniske prøver
- [ ] alle innslag

Så lenge tekst/melodi av vises, vis denne infoen

**Comment by AsgeirSH** [comment]
Fixed in 12cc604
