### ISSUE TITLE
Flytt rapportfiler

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMrapporter#25]
Kan rapportene flyttes til /tmp/phpexcel på serveren?
Og at download.ukm.no symlinker?

**Comment by mariusmandal** [comment]
mistenker enorme rapport-lagre liggende på ukm.no for øyeblikket

**Comment by mariusmandal** [comment]
Helt riktig - slettet akkurat ~1GB tempfiler. Må gjøres bedre

**Comment by AsgeirSH** [comment]
download.ukm.no henter allerede filer fra en mappe på serveren, kan like gjerne gjøre det fra /tmp/phpexcel.

Brukes public_html/temp/-mappen noe sted direkte, slik at den må symlinke til rett mappe?

**Comment by AsgeirSH** [comment]
UKMFestivalen-Faktura henter hvert fall fra public_html/temp/PHPExcel... Og skriver dit også. 
En deprecated rapport fra deprecated repo UKMvideresending bruker samme mappe.
=> 
Mappen /tmp/phpexcel opprettes og chmod 777's.
PHPExcel-default-save endres til /tmp/phpexcel
UKMfestivalen/faktura.php endrer `$objWriter->save(UKM_HOME .'../temp/phpexcel/'.$filnavn);` til `$objWriter->save('/tmp/phpexcel/'.$filnavn);`

**Comment by mariusmandal** [comment]
Løses av UKMNorge/UKMsystem_tools#29
