### ISSUE TITLE
Hent kommunetall fra SSB

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMrapporter#30]
Hvor mange kommuner er det i hvert fylke per år?

Brukes til å generere statistikk
http://ukm.no/wp-admin/network/admin.php?page=UKMrapport_admin&network=monstringer_per_fylke

**Comment by AsgeirSH** [comment]
Løst med innhenting fra DIFIs Datahotell. Import må gjøres manuelt pga spesialkommuner. Close.
