### ISSUE TITLE
Rapport: Juryskjema

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMrapporter#58]
Juryskjema tar utgangspunkt i Teknisk prøve-rapporten.

Det må være mulig å velge ut juryskjema for én eller flere typer innslag. Det må derfor lages en velger på lik linje med hendelse-velgeren, som er standardisert, slik at den kan brukes i flere rapporter.

Målet er at fagpanelet skal kunne skrive ut ei blekke for de som skal bedømme f.eks. utstillingen

Juryskjemaet må ha en page-break per innslag, slik at man får ett ark per innslag.

**Comment by mariusmandal** [comment]
Vi trenger noen flere alternativer på vurderingsskjema, se:
https://github.com/UKMNorge/UKMrapporter/blob/b77c0fdfd75099b486e84500788ea86cee27ce12/rapport/program/program.report.php#L786-L803

**Comment by AsgeirSH** [comment]
![Screenshot 2020-01-09 at 21 25 31](https://user-images.githubusercontent.com/1831028/72102164-9d5b4680-3326-11ea-9cc5-a92ce68ba5bb.png)

Border-less @mariusmandal
