### ISSUE TITLE
Forhåndsvisning vises ikke når man har forhåndsvalgt noe

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMrapporter#62]
Det må byttes preview for å trigge forhåndsvisning, men på page-load vises det ikke. Legg til en trigger som oppdaterer og viser valgt forhåndsvisning @ pageload.

Dette vises i rapporten `Alle innslag`, når man skal velge struktur på utrapporteringen.

**Comment by Jimtrim** [comment]
Fiksa i commit ab2a2d582707131f68766077b3148dc5540363b0
