### ISSUE TITLE
Rapport: Personvern

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMrapporter#67]
Se V1-rapporten i gammelt rapport-repo.

Målet er å liste ut alle innslag hvor én eller flere har sagt nei til foto/film.

**Comment by AsgeirSH** [comment]
Alle innslag for hele mønstringen, eller for hver enkelt hendelse? Eller merke innslaget med alle hendelser det skal være med i og hvilket nummer det har i de? ... Merker innslaget om mer enn èn hendelse er valgt, tror jeg.
