### ISSUE TITLE
Rapport: tekniske prøver

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMrapporter#72]
Må extende program (og inkludere flere valg i tilpass)

**Comment by mariusmandal** [comment]
Se rapporten "alle innslag" for hvilke valg som må være mulig.
I tillegg er det fint om man kan legge til en kommentarbokser. Her må det være følgende checkboxer:
- [ ] lydteknisk
- [ ] lysteknisk
- [ ] generell
og valget for visning (se personer i innslaget - denne må være lik som kompakt/tabell-knappen)
- [ ] liten
- [ ] medium
- [ ] stor

**Comment by AsgeirSH** [comment]
Fixed by 34ca34d
